### ISSUE TITLE
Canvas not being filled properly.

### ISSUE THREAD

**Issue by Irongade** [wrongakram/ar-episode2#5]
Hi, My name is Adeoluwa, and I am a huge fan of your videos, I hope you could give me a few minutes of your time. I am trying to implement a dark background canvas to cover up a video in its background, the code beneath should be able to do that with fill style and the source over, but for some reason it is not, do you have an Idea of how to solve this?

```
let canvas = useRef(null);
    const size = useWindowSize();
    const { currentTheme } = useGlobalStateContext()

    useEffect(() => {
        let renderingElement = canvas.current;
        let drawingElement = renderingElement.cloneNode();

        let drawingCtx = drawingElement.getContext("2d");
        let renderingCtx = drawingElement.getContext("2d");

        let lastX;
        let lastY;

        let moving = false;

        renderingCtx.globalCompositeOperation = "source-over"
        renderingCtx.fillStyle = currentTheme === "dark" ? "#000000" : "#ffffff";
        renderingCtx.fillRect(0,0, size.width, size.height)
        console.log(renderingCtx)

    }, [])
```

This block of code is applying a dark background to the canvas so it can cover up the furrow video behind it
but instead of covering the video up with the dark background canvas ontop of it
It does this instead, its almost like it darkens some areas and leaves the other side alone (the video also stops playing too)
This is the image of the final result

![](https://cdn.discordapp.com/attachments/726931767977705512/827861332647739392/Screenshot_300.png)

@wrongakram Help!!!

**Comment by abhik-b** [comment]
Hi Adeoluwa , I am Abhik and currently I am also facing this same issue , my canvas does not fill up initially in dark mode but fills up initially in light mode . How did you fix your problem ? kindly help me out 🤞

**Comment by Irongade** [comment]
I made a mistake in the code. 

This is the correction in the code below:

`let drawingCtx = drawingElement.getContext("2d");
  let renderingCtx = renderingElement.getContext("2d");
`
